### ISSUE TITLE
낮은 브라우저 버전에서 캘린더 UI 깨짐 현상

### ISSUE THREAD

**Issue by gw-lim** [P1Z7/frontend#81]
## ✏️ 오류사항
사파리 및 크롬 브라우저의 버전이 낮을 경우에 캘린더를 선택했을 때 표시되는 스타일이 깨져서 나타나는 현상이 있습니다.

## 📷 스크린샷
![IMG_7118](https://github.com/P1Z7/frontend/assets/83965026/3966e01f-92e2-4542-a969-23f09849f8df)

**Comment by han-kimm** [comment]
원인
: 네스팅 문법이 지원이 안되는 브라우저 버전에서 문제가 발생합니다.
: 네스팅 문법은 최근에 지원되기 시작한 기능입니다.
![image](https://github.com/P1Z7/frontend/assets/78120157/da3f1a2c-77d0-4f91-958f-396f2305767e)

코드의 문제 지점
`calendarStyle.ts`
```ts
.react-calendar__tile:enabled:focus,
.react-calendar__tile--active {
  abbr {
    background-color: rgba(255, 80, 170, 0.5);
  }
  background: none;
  color: black;
}
```
abbr 태그의 네스팅이 지원이 안되는 브라우저에서는 스타일이 깨집니다.

해결법
-> 네스팅 문법을 [클래스 + 태그] 선택자로 변경합니다.
